"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, Check, ChevronRight, Crown, Hammer, Castle, ScrollText, Map, Shield, Swords, RotateCcw } from "lucide-react";

const DATA: Record<string, any> = {
  fmt:{title:"The Blacksmith's Forge",command:"terraform fmt",icon:Hammer,purpose:"Standardize Terraform configuration using Terraform's canonical formatting.",when:"After writing or editing HCL and before review. It is a safe first step in a local workflow or CI quality gate.",does:["Reformats .tf files","Makes style consistent","Produces cleaner diffs"],not:["Does not validate cloud resources","Does not create a plan","Does not deploy anything"],game:"forge",steps:["Write Terraform","Forge with terraform fmt","Review the clean scroll","Commit the code"],lesson:"Formatting is about consistency, not infrastructure changes."},
  init:{title:"The Castle Gate",command:"terraform init",icon:Castle,purpose:"Prepare a Terraform working directory by initializing its backend, providers and modules.",when:"Run it when you start a new Terraform directory, clone a repository, change backend configuration, or add/change providers or modules.",does:["Initializes the backend","Installs providers","Downloads modules","Creates dependency metadata"],not:["Does not deploy resources","Does not replace plan/apply","Does not make configuration secure by itself"],game:"gate",steps:["Choose the backend","Unlock the provider","Load the modules","Open the gate"],lesson:"Initialization prepares the tools Terraform needs to work; it is not a deployment command."},
  validate:{title:"The Royal Scribe",command:"terraform validate",icon:ScrollText,purpose:"Check whether Terraform configuration is syntactically valid and internally consistent.",when:"After initialization and formatting, before planning. It is excellent for fast local checks and CI.",does:["Checks configuration syntax","Checks internal consistency","Catches configuration mistakes early"],not:["Does not inspect live infrastructure","Does not guarantee cloud policy compliance","Does not create resources"],game:"scribe",steps:["Read the HCL","Spot structural errors","Seal the valid scroll","Send it to the strategist"],lesson:"A valid Terraform configuration can still be insecure or unsuitable for production; validation is one gate, not every gate."},
  plan:{title:"The War Table",command:"terraform plan",icon:Map,purpose:"Preview the changes Terraform proposes before those changes are applied.",when:"After quality, security and policy checks. Use it for review, change visibility and safer approvals.",does:["Compares configuration and state","Shows additions, changes and destructions","Provides a reviewable execution plan"],not:["Does not normally change infrastructure","Does not replace security scanning","Does not mean a plan is automatically safe"],game:"war",steps:["Read desired state","Compare with state","Inspect proposed changes","Approve the battle plan"],lesson:"Plan is the strategic checkpoint between intent and execution."},
  apply:{title:"The Royal Decree",command:"terraform apply",icon:Crown,purpose:"Execute Terraform's proposed changes against the configured infrastructure.",when:"Only after configuration, security checks, policies and the plan have been reviewed and approved.",does:["Executes approved changes","Creates, updates or destroys managed resources","Updates Terraform state"],not:["Should not be the first command after writing code","Does not replace review","Should not bypass production controls"],game:"decree",steps:["Review the plan","Pass security gates","Receive royal approval","Execute the decree"],lesson:"Apply is the point where infrastructure intent becomes real infrastructure."}
};

function GameFrame({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="trial"><div className="trial-heading"><Swords size={18}/><div><div className="eyebrow">INTERACTIVE TRIAL</div><h3>{title}</h3><p>{subtitle}</p></div></div>{children}</div>}
function GameResult({won,reset,text}:{won:boolean;reset:()=>void;text:string}){return <div className={"game-result "+(won?"won":"")}><span>{won?"🏆 Trial mastered":"⚔ Trial in progress"}</span>{won&&<p>{text}</p>}<button onClick={reset}><RotateCcw size={14}/> Reset trial</button></div>}

function ForgeGame(){const target=["Write Terraform","Forge with terraform fmt","Review the clean scroll","Commit the code"];const [placed,setPlaced]=useState<string[]>([]);const add=(x:string)=>!placed.includes(x)&&setPlaced(v=>[...v,x]);const won=placed.join("|")===target.join("|");return <GameFrame title="The Forging Trial" subtitle="Pick a step from the forge floor and place it into the correct order."><div className="slot-row">{target.map((_,i)=><div className={"slot "+(placed[i]?"filled":"")} key={i}>{placed[i]||"Place step "+(i+1)}</div>)}</div><div className="rune-pool">{[...target].reverse().map(x=><button disabled={placed.includes(x)} onClick={()=>add(x)} key={x} className="rune">{x}</button>)}</div><GameResult won={won} reset={()=>setPlaced([])} text="The scroll has been forged in the correct Terraform workflow."/></GameFrame>}
function GateGame(){const pieces=["Backend","Provider plugins","Modules","Working directory"];const [chosen,setChosen]=useState<string[]>([]);const add=(x:string)=>!chosen.includes(x)&&setChosen(v=>[...v,x]);const won=chosen.length===4;return <GameFrame title="Open the Castle Gate" subtitle="Select every piece terraform init prepares. Your choices are placed into the gate inventory."><div className="gate-board"><div className="gate-door">{won?"🏰 GATE OPEN":"🔒 GATE LOCKED"}</div><div className="inventory">{chosen.map(x=><span key={x}>✓ {x}</span>)}</div></div><div className="rune-pool">{pieces.map(x=><button disabled={chosen.includes(x)} onClick={()=>add(x)} key={x} className="rune">{x}</button>)}</div><GameResult won={won} reset={()=>setChosen([])} text="The working directory is prepared: backend, providers and modules are ready."/></GameFrame>}
function ScribeGame(){const statements=[["resource \"aws_s3_bucket\" \"vault\" {","valid"],["resource aws_s3_bucket vault {","invalid"],["variable \"region\" { type = string }","valid"],["resource = \"aws_instance\"","invalid"]];const [marked,setMarked]=useState<Record<number,string>>({});const mark=(i:number,v:string)=>setMarked(s=>({...s,[i]:v}));const won=statements.every((s,i)=>marked[i]===s[1]);return <GameFrame title="The Scribe's Trial" subtitle="Inspect each scroll fragment. Place the Valid or Invalid seal on it."><div className="scroll-list">{statements.map(([code,answer],i)=><div className="scroll-row" key={code}><code>{code}</code><div><button className={marked[i]==="valid"?"seal selected":"seal"} onClick={()=>mark(i,"valid")}>✓ VALID</button><button className={marked[i]==="invalid"?"seal danger selected":"seal danger"} onClick={()=>mark(i,"invalid")}>✕ INVALID</button></div><small>{marked[i]?(answer===marked[i]?"Correct seal":"Wrong seal — inspect the scroll again"):""}</small></div>)}</div><GameResult won={won} reset={()=>setMarked({})} text="The Royal Scribe has confirmed the configuration's structural integrity."/></GameFrame>}
function WarGame(){const target=["+ aws_s3_bucket.vault","+ aws_s3_bucket_public_access_block.vault","~ aws_s3_bucket.vault tags"];const [placed,setPlaced]=useState<string[]>([]);const add=(x:string)=>!placed.includes(x)&&setPlaced(v=>[...v,x]);const won=placed.join("|")===target.join("|");return <GameFrame title="The War Table" subtitle="Place the plan runes in the order a reviewer should read the proposed changes."><div className="battle-map"><div className="map-label">PROPOSED PLAN</div>{target.map((_,i)=><div className="battle-slot" key={i}>{placed[i]||"Awaiting rune"}</div>)}</div><div className="rune-pool">{target.map(x=><button disabled={placed.includes(x)} onClick={()=>add(x)} key={x} className="rune">{x}</button>)}</div><GameResult won={won} reset={()=>setPlaced([])} text="The battle plan is understood: review additions and changes before execution."/></GameFrame>}
function DecreeGame(){const stages=["Plan reviewed","Security gate passed","Policy gate passed","Royal approval"];const [done,setDone]=useState<string[]>([]);const next=stages[done.length];const won=done.length===stages.length;return <GameFrame title="Seal the Royal Decree" subtitle="Complete each gate in order. Only then may terraform apply execute the decree."><div className="decree-stages">{stages.map((x,i)=><button key={x} disabled={i!==done.length} onClick={()=>setDone(v=>[...v,x])} className={"decree-step "+(done.includes(x)?"done":"")}>{done.includes(x)?"✓":i+1}<span>{x}</span></button>)}</div><div className="decree-scroll">{won?"👑 DECREE SEALED":"⚔ "+(next||"Awaiting royal approval")}<code>{won?"terraform apply":"terraform apply  # locked"}</code></div><GameResult won={won} reset={()=>setDone([])} text="The decree was executed only after review, security and policy gates."/></GameFrame>}

export default function CommandChamber({command}:{command:string}){const data=useMemo(()=>DATA[command]||DATA.fmt,[command]);const Icon=data.icon;return <main className="chamber-shell"><header className="topbar"><Link href="/" className="brand-mark"><Shield size={22}/><span>KNIGHT</span></Link><div className="topbar-note">TERRAFORM CODEX · CHAMBER</div><div className="rank-chip"><Crown size={16}/> Apprentice Knight</div></header><div className="chamber-wrap"><Link href="/" className="back-link"><ArrowLeft size={16}/> Return to Kingdom Map</Link><section className="command-hero"><div className="command-icon"><Icon size={38}/></div><div><div className="eyebrow">TERRAFORM COMMAND · CHAMBER</div><h1>{data.title}</h1><div className="command-line">$ {data.command}</div></div></section><section className="learning-grid"><article className="lore-card"><div className="eyebrow">📜 THE CODEX</div><h2>What is it?</h2><p>{data.purpose}</p></article><article className="lore-card"><div className="eyebrow">🕯 WHEN TO RIDE</div><h2>When is it used?</h2><p>{data.when}</p></article><article className="lore-card"><div className="eyebrow">🛡 WHAT IT DOES</div><h2>Its powers</h2><ul>{data.does.map((x:string)=><li key={x}>✓ {x}</li>)}</ul></article><article className="lore-card warning"><div className="eyebrow">⚠ KNOW ITS LIMITS</div><h2>What it does not do</h2><ul>{data.not.map((x:string)=><li key={x}>✕ {x}</li>)}</ul></article></section><section className="workflow-card"><div><div className="eyebrow">🗺 WHERE IT BELONGS</div><h2>Terraform journey</h2><p>{data.lesson}</p></div><div className="workflow">{data.steps.map((x:string,i:number)=><span key={x}><b>{i+1}</b>{x}{i<data.steps.length-1&&<ChevronRight size={16}/>}</span>)}</div></section>{data.game==="forge"&&<ForgeGame/>}{data.game==="gate"&&<GateGame/>}{data.game==="scribe"&&<ScribeGame/>}{data.game==="war"&&<WarGame/>}{data.game==="decree"&&<DecreeGame/>}</div></main>}
