"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {ChevronRight,Check,X,RotateCcw,Shield,Swords,Crown} from "lucide-react";

type Tool={slug:string;name:string;title:string;cat:string;purpose:string;when:string;vars:string[];answer:string;game:string;backend:string;output:string};
const TOOLS:Tool[]=[
{slug:"fmt",name:"terraform fmt",title:"The Blacksmith's Forge",cat:"Terraform",purpose:"Formats Terraform files into canonical style.",when:"After editing HCL and before review or CI.",vars:["terraform fmt","terraform fmt -check","terraform fmt -diff","terraform fmt -recursive"],answer:"terraform fmt -check",game:"Forge Inspection",backend:"Terraform parses HCL and compares formatting with its canonical formatter.",output:"main.tf"},
{slug:"init",name:"terraform init",title:"The Castle Gate",cat:"Terraform",purpose:"Initializes backend, providers and modules.",when:"First use, after cloning, or after dependency/backend changes.",vars:["terraform init","terraform init -upgrade","terraform init -reconfigure","terraform init -migrate-state"],answer:"terraform init -upgrade",game:"Gate Assembly",backend:"Terraform initializes the backend, resolves providers and installs modules.",output:"Terraform has been successfully initialized!"},
{slug:"validate",name:"terraform validate",title:"The Royal Scribe",cat:"Terraform",purpose:"Checks Terraform syntax and internal consistency.",when:"After init/fmt and before plan.",vars:["terraform validate","terraform validate -json","terraform validate -no-color","terraform validate -json -no-color"],answer:"terraform validate -json",game:"Scroll Inspection",backend:"Terraform loads configuration and provider schemas and validates structure.",output:'{"valid":true,"error_count":0}'},
{slug:"plan",name:"terraform plan",title:"The War Table",cat:"Terraform",purpose:"Previews proposed infrastructure changes.",when:"After quality, security and policy gates, before apply.",vars:["terraform plan","terraform plan -out=tfplan","terraform plan -destroy","terraform plan -refresh-only","terraform plan -target=aws_s3_bucket.vault"],answer:"terraform plan -out=tfplan",game:"Battle Plan",backend:"Terraform reads configuration/state, evaluates dependencies and calculates the change graph.",output:"Plan: 2 to add, 1 to change, 0 to destroy."},
{slug:"apply",name:"terraform apply",title:"The Royal Decree",cat:"Terraform",purpose:"Executes approved Terraform changes.",when:"After plan review and security/policy approval.",vars:["terraform apply","terraform apply tfplan","terraform apply -auto-approve","terraform apply -replace=aws_instance.web"],answer:"terraform apply tfplan",game:"Royal Approval",backend:"Terraform executes the approved graph through provider APIs and writes state.",output:"Apply complete! Resources: 2 added, 1 changed, 0 destroyed."},
{slug:"destroy",name:"terraform destroy",title:"The Last Stand",cat:"Terraform",purpose:"Plans and applies destruction of managed infrastructure.",when:"For intentional, reviewed environment teardown.",vars:["terraform destroy","terraform destroy -auto-approve","terraform destroy -target=aws_instance.web","terraform plan -destroy"],answer:"terraform plan -destroy",game:"Evacuation Trial",backend:"Terraform builds a destruction graph so the blast radius can be reviewed before execution.",output:"Plan: 0 to add, 0 to change, 5 to destroy."},
{slug:"opa",name:"Open Policy Agent",title:"The Royal Council",cat:"Policy",purpose:"Evaluates Rego policy decisions against structured input.",when:"As a policy gate before deployment.",vars:["opa eval","opa eval --data policy.rego","opa eval --input input.json","opa test ."],answer:"opa eval --input input.json",game:"Council Judgment",backend:"OPA loads Rego and evaluates policy against structured input.",output:"true / false / deny:[...]"},
{slug:"conftest",name:"Conftest",title:"The Royal Court",cat:"Policy",purpose:"Tests configuration against Rego policies.",when:"When IaC configuration needs automated policy tests.",vars:["conftest test .","conftest test --policy policy .","conftest test --all-namespaces .","conftest verify"],answer:"conftest test --policy policy .",game:"Courtroom Trial",backend:"Conftest parses configuration, passes structured data to Rego and returns test results.",output:"FAIL - policy.rego / 1 test, 1 failure"},
{slug:"checkov",name:"Checkov",title:"The Shield Inspector",cat:"Security",purpose:"Scans IaC for security and compliance misconfigurations.",when:"During PR/CI before plan/apply.",vars:["checkov -d .","checkov -f main.tf","checkov -d . --framework terraform","checkov -d . --compact"],answer:"checkov -d . --framework terraform",game:"Shield Inspection",backend:"Checkov parses IaC, maps resources to checks and reports failed controls.",output:"Passed checks: 38 / Failed checks: 2"},
{slug:"tfsec",name:"tfsec",title:"The Dark Armory",cat:"Security",purpose:"Statically scans Terraform for security issues.",when:"Before plan/apply and as fast developer feedback.",vars:["tfsec .","tfsec --format json .","tfsec --minimum-severity HIGH .","tfsec --exclude AWS001 ."],answer:"tfsec --minimum-severity HIGH .",game:"Threat Hunt",backend:"tfsec parses Terraform, evaluates rules and filters findings by severity.",output:"HIGH: S3 bucket allows public access"},
{slug:"terrascan",name:"Terrascan",title:"The Watchtower",cat:"Security",purpose:"Scans IaC for security and compliance violations.",when:"In CI/CD and pre-deployment review.",vars:["terrascan scan","terrascan scan -i terraform","terrascan scan -t aws","terrascan scan -d ."],answer:"terrascan scan -i terraform",game:"Watchtower Patrol",backend:"Terrascan parses IaC and evaluates resources against security/compliance rules.",output:"Violation: S3 bucket encryption is not enabled"},
{slug:"tflint",name:"TFLint",title:"The Stablemaster",cat:"Quality",purpose:"Lints Terraform for errors and provider-specific issues.",when:"During development and CI before plan.",vars:["tflint","tflint --init","tflint --recursive","tflint --format compact"],answer:"tflint --init",game:"Stable Inspection",backend:"TFLint loads rules/plugins, parses Terraform and reports lint violations.",output:"warning: variable name should use snake_case"},
{slug:"terraform-docs",name:"terraform-docs",title:"The Royal Archivist",cat:"Documentation",purpose:"Generates documentation from Terraform modules.",when:"When modules change and docs should stay synchronized.",vars:["terraform-docs markdown .","terraform-docs markdown table .","terraform-docs markdown --output-file README.md .","terraform-docs json ."],answer:"terraform-docs markdown --output-file README.md .",game:"Archive Assembly",backend:"terraform-docs reads module metadata and renders variables, outputs and resources.",output:"README.md updated with Inputs / Outputs / Resources"},
{slug:"pre-commit",name:"pre-commit",title:"The Gatekeeper",cat:"Automation",purpose:"Runs configured repository hooks before commits or on demand.",when:"At commit time and in CI.",vars:["pre-commit run","pre-commit run --all-files","pre-commit install","pre-commit autoupdate"],answer:"pre-commit run --all-files",game:"Gate Chain",backend:"pre-commit reads .pre-commit-config.yaml, creates hook environments and runs configured tools.",output:"terraform_fmt...Passed / tflint...Passed / checkov...Passed"},
{slug:"terragrunt",name:"Terragrunt",title:"The Kingdom Steward",cat:"Orchestration",purpose:"Adds DRY configuration, dependency management and orchestration around Terraform.",when:"For multiple modules/environments with shared configuration.",vars:["terragrunt init","terragrunt plan","terragrunt apply","terragrunt run --all plan","terragrunt run --all apply"],answer:"terragrunt run --all plan",game:"Kingdom Orchestration",backend:"Terragrunt reads terragrunt.hcl, resolves dependencies and invokes Terraform across the graph.",output:"module-a: Plan: 1 to add / module-b: Plan: 2 to change"}
];

const FLOW=["Code","fmt","init","validate","TFLint","Security scans","OPA / Conftest","plan","Approval","apply"];
const catIcon=(c:string)=>c==="Security"?"🛡️":c==="Policy"?"📜":c==="Documentation"?"📚":c==="Automation"?"⛓️":c==="Orchestration"?"🏰":"⚔️";

function Logo(){return <div className="logo"><div className="fallback">⚔</div><img src="/knight-logo.png" alt="KNIGHT logo" onError={e=>e.currentTarget.style.display="none"}/><span><b>KNIGHT</b><small>Terraform Kingdom</small></span></div>}

export default function KingdomHome({initialTool}:{initialTool?:string}){
 const [page,setPage]=useState(initialTool?"tool":"home"); const [slug,setSlug]=useState(initialTool||"fmt");
 const open=(s:string)=>{setSlug(s);setPage("tool")}; const tool=TOOLS.find(t=>t.slug===slug)||TOOLS[0];
 return <main className="app"><header><Logo/><nav><button onClick={()=>setPage("home")}>🏰 Kingdom</button><button onClick={()=>setPage("workflow")}>🗺 Workflow</button><button onClick={()=>setPage("matrix")}>📊 Matrix</button></nav><span className="rank">👑 Apprentice Knight</span></header>{page==="home"&&<Home open={open}/>} {page==="workflow"&&<Workflow/>} {page==="matrix"&&<Matrix open={open}/>} {page==="tool"&&<ToolView tool={tool}/>}</main>
}

function Home({open}:{open:(s:string)=>void}){return <><section className="hero"><div><small className="eyebrow">⚔ DARK FANTASY · PROFESSIONAL DEVSECOPS</small><h1>The Kingdom of <em>KNIGHT</em></h1><p>Master Terraform and DevSecOps through medieval strategy. Every command and tool has its own chamber, workflow, variations, backend story, output and unique trial.</p><button className="gold" onClick={()=>open("fmt")}>Enter the Kingdom <Swords size={17}/></button></div><div className="castle">☾<strong>♜</strong><b>KNIGHT</b></div></section><section className="map"><div className="title"><span>THE ROYAL ROAD</span><h2>All Chambers</h2></div><div className="cards">{TOOLS.map(t=><button className="card" key={t.slug} onClick={()=>open(t.slug)}><i>{catIcon(t.cat)}</i><small>{t.cat}</small><b>{t.title}</b><code>{t.name}</code><span>{t.game}</span></button>)}</div></section></>}

function Workflow(){return <section className="page"><small className="eyebrow">🗺 THE GRAND STRATEGY MAP</small><h1>Overall Tools Workflow</h1><p className="lead">A concise route from source code to controlled infrastructure, with quality, security and policy surrounding the Terraform path.</p><div className="overall">{FLOW.map((x,i)=><div className="node" key={x}><strong>{i+1}</strong><span>{x}</span>{i<FLOW.length-1&&<ChevronRight/>}</div>)}</div><div className="panel"><h2>Tool realms</h2><div className="realms"><b>⚒ Quality: terraform fmt · validate · TFLint</b><b>🛡 Security: tfsec · Checkov · Terrascan</b><b>📜 Policy: OPA · Conftest</b><b>📚 Documentation: terraform-docs</b><b>⛓ Automation: pre-commit</b><b>🏰 Orchestration: Terragrunt</b></div></div></section>}

function Matrix({open}:{open:(s:string)=>void}){return <section className="page"><small className="eyebrow">📊 THE ROYAL MATRIX</small><h1>Command & Tool Comparison</h1><p className="lead">A quick reference for selecting the right command or tool.</p><div className="table"><table><thead><tr><th>Tool / Command</th><th>Realm</th><th>Purpose</th><th>Infrastructure change</th><th>Trial</th></tr></thead><tbody>{TOOLS.map(t=><tr key={t.slug}><td><button onClick={()=>open(t.slug)}>{t.name}</button></td><td>{t.cat}</td><td>{t.purpose}</td><td>{t.name==="terraform apply"||t.name==="terraform destroy"?"Yes / potentially":"No"}</td><td>{t.game}</td></tr>)}</tbody></table></div></section>}

function ToolView({tool}:{tool:Tool}){const [picked,setPicked]=useState<string|null>(null);const [done,setDone]=useState(false);const [tick,setTick]=useState(0);const vars=useMemo(()=>[...tool.vars].sort(()=>Math.random()-.5),[tool.slug,tick]);const finish=()=>{if(picked)setDone(true)};return <section className="page tool"><Link href="/" className="back">← Return to Kingdom</Link><div className="toolHead"><div><small className="eyebrow">{tool.cat.toUpperCase()} · {tool.game.toUpperCase()}</small><h1>{tool.title}</h1><code>$ {tool.name}</code></div><div className="crest">⚔</div></div><div className="learn"><article><small>📜 WHAT IT IS</small><p>{tool.purpose}</p></article><article><small>🕯 WHEN USED</small><p>{tool.when}</p></article><article><small>🛡 WHAT IT DOES</small><p>Use it for the specific role described in this chamber and combine it with the other gates rather than treating it as a replacement for them.</p></article><article className="warning"><small>⚠ LIMITS</small><p>It does not replace the other quality, security, policy or deployment controls.</p></article></div><div className="panel"><small className="eyebrow">🗺 COMMAND VARIATIONS</small><div className="exactFlow">{tool.vars.map((v,i)=><span key={v}><b>{i+1}</b>{v}</span>)}</div></div><div className="game"><div className="gameTitle"><div><small className="eyebrow">⚔ {tool.game.toUpperCase()}</small><h2>Drag the correct variation into the chamber</h2><p>Answers are hidden. Pick or drag a variation, then complete the trial. Only after completion will KNIGHT reveal whether it is correct.</p></div><span>♜</span></div><div className="drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setPicked(e.dataTransfer.getData("text"))}}>{picked?<code>{picked}</code>:"Drop a command variation here"}</div><div className="vars">{vars.map(v=><button draggable onDragStart={e=>e.dataTransfer.setData("text",v)} onClick={()=>setPicked(v)} className={picked===v?"chosen":""} key={v}>{v}</button>)}</div><div className="actions"><button className="gold" disabled={!picked} onClick={finish}>Complete Trial <Check size={16}/></button><button className="reset" onClick={()=>{setPicked(null);setDone(false);setTick(x=>x+1)}}><RotateCcw size={15}/> Reset</button></div>{done&&<div className={picked===tool.answer?"correct":"wrong"}>{picked===tool.answer?<><Check/><div><b>Correct — trial mastered.</b><p>Your selection matches the scenario.</p></div></>:<><X/><div><b>Wrong selection.</b><p>You chose <code>{picked}</code>. The correct variation is <code>{tool.answer}</code>.</p></div>}</div>}</div>{done&&<div className="after"><div className="panel"><small className="eyebrow">🧠 AFTER THE TRIAL · BACKEND</small><p>{tool.backend}</p></div><div className="panel"><small className="eyebrow">💻 EXPECTED OUTPUT</small><pre>{tool.output}</pre></div></div>}</section>}
